### ISSUE TITLE
Encoder Premium

### ISSUE THREAD

**Issue by batdanilo** [Azure/Azure-Media-Services-Explorer#100]
Hi all,
i'm trying to encode a video with the premium encoder, but when i upload the default workflow files and then try to encode, i receive always this error :"MEPW v1.32 - H264 Progresssive Download MP4.workflow', Error : UserInput : File type or codec not supported."
Thank's
Danilo

**Comment by xpouyat** [comment]
Closing this issue. Please open a support ticket instead.
