### ISSUE TITLE
Azure Media Services v3 SDK and Azure Media Services Explorer

### ISSUE THREAD

**Issue by lfraile** [Azure/Azure-Media-Services-Explorer#102]
Hello I have been playing lately with the new SDK (https://docs.microsoft.com/en-us/azure/media-services/latest/) but it seems when I create assets, encode and publish them with the new SDK (with .NET) the assets doesn't seem to appear correctly in Azure Media Services Explorer, although I can see them using the locators provided with the new SDK and Azure Media Player, but the appear as *empty* assets in the Explorer.

Is there something wrong with the assets created with the new SDK?

**Comment by fvneerden** [comment]
Hi,

Azure Media Services Explorer is not (yet) compatible with api v3. Any asset/channel created using the api v3 will not show correctly in AMSE for V2.

**Comment by xpouyat** [comment]
I am working on a version of AMSE for AMS v3. A preview should come this month I think

**Comment by xpouyat** [comment]
AMSE Preview for AMS v3 is available here : https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.0.0.12
Branch is rpv3 https://github.com/Azure/Azure-Media-Services-Explorer/tree/rpv3
