### ISSUE TITLE
JSON file is not generated in Unicode

### ISSUE THREAD

**Issue by kazshi** [Azure/Azure-Media-Services-Explorer#103]
I run the Media Analytics OCR for a video containing Japanese text and text in generated JSON file is displayed in Unicode code (\u30B9\u30C8\u30EA... for example). The Unicode code characters are converted to Japanese once I reformat the text in the AMSE (click Edit on Asset Files tab, and click Format data button). Looks like file encoding to JSON file is not set properly - I'm not sure if it's by design/possible to configure - are there any ways to generate JSON file in Unicode?

**Comment by xpouyat** [comment]
Thanks for your feedback. We are looking into this.

**Comment by kazshi** [comment]
@xpouyat Do you have any progress on this?  Thanks.

**Comment by xpouyat** [comment]
I am checking again with the product team. Sorry for the delay.

**Comment by xpouyat** [comment]
We identified the issue with the OCR processor. A fix is currently under development. Thanks for reporting this!

**Comment by kazshi** [comment]
@xpouyat Thanks for your update. I'll let my customer know it. Do you have any ETA for the fix?
