### ISSUE TITLE
The remote server returned an error:(401) Unauthorized

### ISSUE THREAD

**Issue by mcgraf** [Azure/Azure-Media-Services-Explorer#105]
I keep getting this error when trying to login to my Azure Media services account.
 It is a freshly installed 4.3.4.0 version and when i click connect after filling in the tenant and endpoint a screen to login appears and disappears instantly without allowing me to choose an account and i get this error

**Comment by ashergr** [comment]
@mcgraf , I'm dealing with the same issue. Did you find any solution?

**Comment by xpouyat** [comment]
Hello,
With the new AMSE v5 version for AMS v3 you can select the user when connecting to Azure AD. There is no way to do the same with AMSE v4 because of the a different way to manage the authentication with Azure AD from the AMS SDK.

**Comment by mcgraf** [comment]
@ashergr  Well personally I stopped using it because the project I wanted to use it for ended, and since @xpouyat says that it is fixed in the newer version I consider this issue closed.
