### ISSUE TITLE
AMSE v5.0.0.12 bugs.

### ISSUE THREAD

**Issue by znrk** [Azure/Azure-Media-Services-Explorer#106]
AMS Explorer v 5.0.0.0

  - Authentication mode: "Interactive" causes an authentication error.
show the "Add an Account" dialog, I chose mode is "manual".
-> input AMS Resource Id, Region and tennant Id.
-> back to first dialog, I click "Connect".
-> showing login error dialog. "Operation returned an invalid status code 'Unauthorized.'"

  - Where can I check the streaming policy?

  - LiveOutput can not be created.
  -> I can create it from Azure CLI.
However, it is very troubling that LiveOutput can not be created from AMS Explorer for v3 when trouble occurs.

**Comment by xpouyat** [comment]
Hello,

I tested authentication mode interaction from a manual entry. It does work for me.
AMS Resource ID looks like: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/Default-Media-WestEurope/providers/Microsoft.Media/mediaservices/myaccount
Region looks like: West Europe
and the Azure tenant ID is a guid like : 00000000-0000-0000-0000-000000000000
(it is displayed on the top right on your account in Azure portal).


Streaming policy display : the work in under development

Live output cannot be created : I can reproduce. Thanks for the report !

**Comment by xpouyat** [comment]
I identified the issue regarding "Operation returned an invalid status code 'Unauthorized.'"
It is because the tenant id was not passed when getting the token.
Do you want to test a test build that fixes these issues ?

**Comment by znrk** [comment]
Thank you very match!

> Do you want to test a test build that fixes these issues ?

Yes, I want to test.

**Comment by xpouyat** [comment]
Please test this version: https://amsexplorer.blob.core.windows.net/release/AMSExplorerSetup_v5.0.0.13.exe
Thanks !

**Comment by xpouyat** [comment]
New release (v5.0.0.16) should solve these issues.
