### ISSUE TITLE
Error in AMS 4.3.4.0

### ISSUE THREAD

**Issue by mcgraf** [Azure/Azure-Media-Services-Explorer#108]
I set up face detector job on 3.6gb mkv video i uploaded using AMS and i get this error "Error : ErrorDownloadingInputAssetServiceFailure : An error has occurred. Stage: DownloadFile. Code: System.IO.IOException." it does this every time i run this job
Any ideas?

**Comment by xpouyat** [comment]
Hello,
I am not sure that MKV can be taken as an input by Face Detection processor.
Did you try to process a MP4 file with Face Detection (may be try to convert the MKV to MP4 using Media Encoder Standard, with a single bitrate preset).

**Comment by mcgraf** [comment]
My mistake, I just found in the documentation that it only supports MP4, MOV, WMV.
