### ISSUE TITLE
AMSEv5: Issue in "Asset deletion" dialog when cancelling

### ISSUE THREAD

**Issue by shigeyf** [Azure/Azure-Media-Services-Explorer#110]
Even when selecting "Cancel" button in "Asset deletion" dialog, deleting assets happened.

![2019-03-29_003049](https://user-images.githubusercontent.com/6917167/55241442-6677e080-527e-11e9-89f9-af971c4c7a1f.png)

**Comment by xpouyat** [comment]
oh.. Sorry. Fixing this now.

**Comment by xpouyat** [comment]
https://github.com/Azure/Azure-Media-Services-Explorer/commit/342fd1ed099200906272f4287513ed5e4c7c2fce
