### ISSUE TITLE
error in search

### ISSUE THREAD

**Issue by rodrigoitcore** [Azure/Azure-Media-Services-Explorer#114]
Hi, I'm trying to search for the word "Quimica" and am returning incorrect results

![V3search](https://user-images.githubusercontent.com/52412761/60441856-40037180-9bee-11e9-91f6-83b9f6f3c46a.png)

Thank You!!

**Comment by xpouyat** [comment]
Hello,
I think the result is expected. It displays all assets with a name "greater" then Quimica, which means the names after Quimica in alphabetic order.
I did some changes in the code and the next version will propose a new option "startwith" with uses odata options combined 'greater than' and 'less than'.

**Comment by rodrigoitcore** [comment]
Hi,
thanks for the interaction

De: Xavier Pouyat <notifications@github.com>
Enviada em: terça-feira, 2 de julho de 2019 09:01
Para: Azure/Azure-Media-Services-Explorer <Azure-Media-Services-Explorer@noreply.github.com>
Cc: Rodrigo Toledo <rodrigo.toledo@itcore.com.br>; Author <author@noreply.github.com>
Assunto: Re: [Azure/Azure-Media-Services-Explorer] error in search (#114)


Hello,
I think the result is expected. It displays all assets with a name "greater" then Quimica, which means the names after Quimica in alphabetic order.
I did some changes in the code and the next version will propose a new option "startwith" with uses odata options combined 'greater than' and 'less than'.

**Comment by rodrigoitcore** [comment]
Xavier i can filter by “description” label? I need this!

Fábio Vello
+55 11 99242-4288
Enviado do meu iPhone

Em 2 de jul de 2019, à(s) 09:04, Rodrigo Toledo <rodrigo.toledo@itcore.com.br<mailto:rodrigo.toledo@itcore.com.br>> escreveu:

Hi,
thanks for the interaction

De: Xavier Pouyat <notifications@github.com<mailto:notifications@github.com>>
Enviada em: terça-feira, 2 de julho de 2019 09:01
Para: Azure/Azure-Media-Services-Explorer <Azure-Media-Services-Explorer@noreply.github.com<mailto:Azure-Media-Services-Explorer@noreply.github.com>>
Cc: Rodrigo Toledo <rodrigo.toledo@itcore.com.br<mailto:rodrigo.toledo@itcore.com.br>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Assunto: Re: [Azure/Azure-Media-Services-Explorer] error in search (#114)


Hello,
I think the result is expected. It displays all assets with a name "greater" then Quimica, which means the names after Quimica in alphabetic order.
I did some changes in the code and the next version will propose a new option "startwith" with uses odata options combined 'greater than' and 'less than'.

**Comment by xpouyat** [comment]
It is not possible to filter by description label because the v3 AMS API does not allow this.
See https://docs.microsoft.com/en-us/azure/media-services/latest/entities-overview#filteringordering

**Comment by johndeu** [comment]
That's mostly due to SQL backend performance on table scans of the description field.  Description field in V3 shows the old v2 "Name" when migrating forward, but for V3 customers it can ALSO be used for just a generic description of the asset, so it is not perfomant column to query on. 

For searching in V3 for assets from V2, you should just use the GUID value portion of the older v2 Asset ID that begins with "nb:cid:UUID:<GUID>"

**Comment by johndeu** [comment]
One more comment - AMS is not really built to be an asset management search system. Highly recommend that you offload the search part of your application to a more appropriate system like Azure Search or even just CosmosDB to store more asset metadata and map to ID's in AMS.

**Comment by rodrigoitcore** [comment]
![image](https://user-images.githubusercontent.com/52412761/60673651-9ec72600-9e4e-11e9-9119-e732f081dcf7.png)

Hi, the platform hangs when doing the search by "resource code"

tks

**Comment by xpouyat** [comment]
Yes, you are right. Investigating....

**Comment by xpouyat** [comment]
Ok, problem was in AMSE code. I am updating it and will publish a new version soon

**Comment by xpouyat** [comment]
New version has been published. Please update to v5.0.5.0

**Comment by rodrigoitcore** [comment]
Thank You!!!
