### ISSUE TITLE
0 byte uploaded in cloud 5.0.6 version

### ISSUE THREAD

**Issue by KRK2011** [Azure/Azure-Media-Services-Explorer#116]
I am using Azure Media Services Explorer 5.0.6, when I upload an asset in the tool it shows size is 4mb, but when I go to Azure Portal it shows 0 bytes size, due to this I am not able do any encoding.

**Comment by xpouyat** [comment]
Hello,
Unfortunately, this is expected. AMSE v5 uses the new AMS v3 API which relies on Azure storage blobs to list the files in the asset (there is no more AMS asset file object in v3).
The portal uses the v2 API and expects AMS asset files. In your case, the asset created with v3 is viewed from v2 and so does not expose asset files and displayed size is 0. But in reality, the asset has storage blobs and can be used without problem with AMS v3 for processing or streaming.

**Comment by KRK2011** [comment]
Thank you for the quick response, When I use the older version for AMSE work perfectly.

    On Thursday, July 25, 2019, 03:01:07 PM EDT, Xavier Pouyat <notifications@github.com> wrote:  
 
 
Hello,
Unfortunately, this is expected. AMSE v5 uses the new AMS v3 API which relies on Azure storage blobs to list the files in the asset (there is no more AMS asset file object in v3).
The portal uses the v2 API and expects AMS asset files. In your case, the asset created with v3 is viewed from v2 and so does not expose asset files and displayed size is 0. But in reality, the asset has storage blobs and can be used without problem with AMS v3 for processing or streaming.

**Comment by xpouyat** [comment]
The produc team is planning to update the portal to reduce the confusion.
