### ISSUE TITLE
Need function to upload caption

### ISSUE THREAD

**Issue by towhereur** [Azure/Azure-Media-Services-Explorer#117]
There's a function like analyze to make caption, but I don't want to analyze it but caption upload.
azure portal has function "caption upload", but it returns error when I upload vtt file.
Error messages like below.
"Asset Files are not supported for Assets created though the Media Services ARM API. File metadata for new Assets can be set and retrieved using the Azure Storage APIs."
So I want you to make function "caption upload" in AMSE.

Anyone have workaround? Any suggestions?

**Comment by xpouyat** [comment]
Hello, in both versions (v4 and v5) of AMSE, you can upload captions from the asset info / files tab.
You can also use the feature "upload file(s) to selected asset(s)" to do the same.
If you want to apply dynamic DRM to the video asset, then you probably need to store captions in a separate asset.
