### ISSUE TITLE
Dictionary

### ISSUE THREAD

**Issue by rodrigoitcore** [Azure/Azure-Media-Services-Explorer#119]
Hello

I have a question, why I did not find, can we edit the word dictionary?

Note: Same as Online Video Indexer

**Comment by xpouyat** [comment]
Hello,
AMS v3 Audio Analysis preset does not support this, while Video Indexer supports it.
https://docs.microsoft.com/en-us/azure/media-services/video-indexer/compare-video-indexer-with-media-services-presets
