### ISSUE TITLE
Possible to Subclip ALL Bitrates?

### ISSUE THREAD

**Issue by jlking92887** [Azure/Azure-Media-Services-Explorer#120]
Do you know, if it is possible (now or in the future) to subclip an asset while keeping multi-bitrates? 

Right now we have the ability to keep ONLY the top bitrate while subclipping, and then re-encode the file, with AMS v2 we were able to Subclip/Trim while keeping ALL bit rates. 

We are hoping to subclip an asset while keeping all bitrates without reencoding the asset.

**Comment by xpouyat** [comment]
Hello,
Subclipping all the bitrates is not possible today with AMS v3. The product team is aware of this gap and plans to bring the feature at some point. No timeline yet.
