### ISSUE TITLE
Problem transcript name

### ISSUE THREAD

**Issue by rodrigoctoledo** [Azure/Azure-Media-Services-Explorer#121]
Hello, after transcribing the video for subtitles, the reference to the original file name is lost, making the search impossible.
Is there any reference besides the name?

Tks

**Comment by xpouyat** [comment]
Thanks for the feedback. This is for AMSE v5, right ?
I am thinking about changing the output asset name generation to reuse the name of the source asset and append unique name.
<source asset name>-<transform name>-<unique short GUID>

For example, if source asset is 
"uploaded-ef769b5f-41b9"
then output asset for video analyzer could be named
"uploaded-ef769b5f-41b9-VideoAnalyzer-en-US-28d32518-32c0"

What do you think ?

**Comment by rodrigoctoledo** [comment]
Very good, the same happens in the video encoding process for other qualities, is it possible to solve?

Tks

**Comment by xpouyat** [comment]
AMSE does use the source asset name in the output name
