### ISSUE TITLE
Encoding Single Bitrate 1080P Subclipped Asset Always Errors

### ISSUE THREAD

**Issue by JoshKing87** [Azure/Azure-Media-Services-Explorer#122]
We are trying to encode a 1080p asset that has previously been subclipped with the AMSE tool. The asset is a Single Bitrate MP4(1) and no matter which built in encoding preset we select, the Job errors.

Every job we run returns with error: 
Output 'BuiltInStandardEncoderPreset_0', Error : Microsoft.Azure.Management.Media.Models.JobError : Problem with input and configuration combination, fix the configuration and retry with the same input, or change input to match the configuration.

Steps to reproduce:

1. Live stream with 1080p Azure Live Encoding
2. Subclip 20 min clip of Top Bitrate to create new asset
3. Create Encode Job, with Any of the built in AMS EncoderNamedPreset Transforms
4. Job errors with above

Is encoding a previously subclipped 1080p asset possible at this time with AMS v3?

**Comment by xpouyat** [comment]
I think it is a known issue and it will be fixed by the AMS product team. In the meantime, you can try to delete, from the asset created in step #2, all the blobs except the MP4 file. Then AMS MES should be able to take it as a source asset.

**Comment by jlking92887** [comment]
Thanks, we will try this. Is there any expected ETA when it will be fixed?

**Comment by anilmur** [comment]
Question: why are you doing this as a two-step process? You can perform a subclip+named-preset encode directly off of the live archive (the highest bitrate video layer would be used).

**Comment by jlking92887** [comment]
For our onsite process at Microsoft Events, we have a multi-step delivery process for delivery of OnDemand files.

Our current process/code workflow would be as follows:

1. Stream the Session with 720p (v2)/1080p (v3) live encoding to a web platform.
2. Azure timer function runs every 15 minutes to subclip a session time block/chunk out of the live output stream that has 15 minute before and after padding
3. Engineers on site then trim this newly created asset, setting in and out points with our tools and submitting another subclip job to create another smaller version of the original session asset file .
4. This new smaller version of the asset then goes through Quality Control and published for On Demand consumption in less than 6 hours after the session physically occurred.

Our On Demand deliverable NEEDS to have multi-bitrate playback, and we are able to easily support this with v2, so we are hoping to support this with v3.

Does this answer your question?

**Comment by anilmur** [comment]
Thanks for the details! Will follow up with engineering
