### ISSUE TITLE
Cannot delete Streaming endpoint

### ISSUE THREAD

**Issue by cchanms** [Azure/Azure-Media-Services-Explorer#123]
I am using V5.0.12.0
When I right click one of already stopped Streaming endpoint(s) and select Delete streaming endpoint(s).
The message shows
[10/21/2019 3:34:45 PM] Deleting streaming endpoints(s) : xxxxxep1...
[10/21/2019 3:34:48 PM] Streaming endpoint(s) deleted : xxxxxep1.

But the endpoint is still there.

Repro steps:

1. Go to Streaming endpoint(s) tab
2. Create streaming endpoint...
3. Enter a name and hit Create streaming endpoint
4. Wait the creation has completed and select the just created streaming endpoint
5. Right click it and select Delete streaming endpoint(s)
6. See the message showing Streaming endpoint(s) deleted: xxxxxx

Expect:
The endpoint is deleted

Actual:
The endpoint is still there.

**Comment by xpouyat** [comment]
New version released today.
