### ISSUE TITLE
Could  we support the Chinese UI?

### ISSUE THREAD

**Issue by eaglezzb** [Azure/Azure-Media-Services-Explorer#124]
we need chinese  UI

**Comment by xpouyat** [comment]
Hello,
Some of the UI has been translated to Japanese. So the infrastructure is in place for multi language. Do you have the capability and time to translate the English strings to Chinese ? Most of the UI strings are in resource files. I can indicate you how to do the translation and make a pull request. Is it for AMSE v5 ?

**Comment by eaglezzb** [comment]
ok,   We can provide a translation, please tell us how to contribute to this project(L18n) ?

**Comment by eaglezzb** [comment]
appreciate thanks

**Comment by xpouyat** [comment]
I created a branch for the Chinese UI work.
https://github.com/Azure/Azure-Media-Services-Explorer/tree/chinese-UI
I recommend you to use ResXManager to do the translation https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager
Please change only the Chinese strings and do pull request to this branch once it's done.

**Comment by xpouyat** [comment]
For information, if you want to force a language which is different from the OS UI, you can using the /language parameter. Use 'ja' for Japanse, 'zh' for Chinese and 'en' for English.
Example:
"C:\Program Files (x86)\Microsoft Corporation\Azure Media Services Explorer for v3\AMSExplorer.exe" /language:ja

**Comment by xpouyat** [comment]
Chinese UI is in branch https://github.com/Azure/Azure-Media-Services-Explorer/tree/chinese-UI but sorry the code cannot be merged into master as it not complete and not approved.
