### ISSUE TITLE
Face Reactor Feature in v3

### ISSUE THREAD

**Issue by JPain** [Azure/Azure-Media-Services-Explorer#125]
Face reactor feature is available for the v2 API version 4.3.10.0
![image](https://user-images.githubusercontent.com/6144262/68585416-1569d500-047a-11ea-8b68-1a00898bad6d.png)

This doesn't seem to be implemented as of 5.0.12.0.
That, or it's moved and I can't find it.

**Comment by xpouyat** [comment]
Face Redactor is not available in the AMS v3 API.

**Comment by JPain** [comment]
> 
> 
> Face Redactor is not available in the AMS v3 API.

Ah. I did suspect, but I couldn't find any confirmation of it in the docs.
I'll close. @xpouyat If you have any info on if it's planned to be in v3 or it's being phased out, that'd help. Thanks!
