### ISSUE TITLE
AMSE is abonimably slow

### ISSUE THREAD

**Issue by hexarcate** [Azure/Azure-Media-Services-Explorer#129]
I only have a few dozen assets, but even when filtered to those modified in the past 24 hours, the grid takes an eternity to populate, 5-10 minutes per row. In fact, all tabs are extremely slow to populate. It's the same drilling into individual assets. A simple operation, like looking up the locators for a single asset can take ten minutes. I'm using a distant blob storage location, but that can't be the issue because a) my own web application, which interacts with the same AMS account using the .NET SDK, shows no performance issues, and b) the portal, although it does not support all of v3 functionality, nevertheless lists the assets in sub-second time. My machine is not resource constrained, so that leaves the application as the only culprit I can identify, unless AMS is throttling the requests? But why would it only affect AMSE? I am using v5.0.13.0 for AMS v3.

**Comment by xpouyat** [comment]
Hello,
Sorry for the performance issue. Can you installer Fiddler and see if the performance comes from some AMS v3 REST request(s), and if yes, which kind of AMS request(s) ?

**Comment by hexarcate** [comment]
Hi @xpouyat. Examining the traffic in Fiddler revealed a very interesting pattern. Individual calls are not the issue. They take about 200ms each, and all return 200. It also starts out quickly enough, but as the grid load progresses, I see more and more of the same calls issued. For instance, for the first couple of assets, I see the request to list streaming locators issued four times for each asset, which is strange in itself, but things get really out of hand as more assets get loaded. By the fifteenth row, dozens and dozens of the same request are being issued. It's not just listStreamingLocators operation by any means though. I see the same geometric progression with everything. For some reason, AMSE is also calling blob storage and listing the blobs when that shouldn't be necessary in the Assets view. And these blob list calls multiply in like manner from a couple per asset to easily a hundred in short order. It's this geometric progression of identical API calls that quickly causes the application to appear to stop working entirely, but in fact it's still issuing requests, in ever greater numbers.

**Comment by xpouyat** [comment]
Thanks. Listing the blobs is expected as AMSE use this data to define the asset type and display it in the asset grid. Normally, AMSE should only list the assets that are displayed.
I will check the pattern on my side to see if there is a code issue.

**Comment by xpouyat** [comment]
Hello,
I started to optimize the code to reduce the REST calls. In the case of listing the assets, updated code can reduce up to 4 time the number of calls. https://github.com/Azure/Azure-Media-Services-Explorer/commit/a82693c534ad55fd6a3bfcefa6504b9f797fb58e

**Comment by xpouyat** [comment]
Hello,
The new release contains the optimization.
https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.0.15.0

**Comment by hexarcate** [comment]
I've updated my installation, but I'm not seeing much improvement. The application becomes unresponsive after a couple of minutes of populating the asset grid. The asset names are loaded very quickly but populating the other columns is where it bogs down. And I can still see dozens of identical API calls in Fiddler.

**Comment by xpouyat** [comment]
Can you tell me in which region is your AMS account, and from which location you run AMSE ? Thanks

**Comment by hexarcate** [comment]
The AMS is in Hong Kong. I am in Salt Lake City. But I’m very sure the problem is not latency. I have an internal web application I’ve written that interacts with the AMS API. Like AMSE, it also lists assets. I have them organized into virtual folders, so I’m not trying to load them all at once, but even so, there are no performance issues. Also, the roundtrip for the calls that AMSE makes it reasonable: it averages ~200ms per call, consistently. The issue is the repeating calls. I see the same calls to the same resources made many times over while I am on the asset tab.

**Comment by xpouyat** [comment]
Current version is based on .Net 5, which should have better performances.
Next release ships some code optimizations for displaying the assets.
