### ISSUE TITLE
V2 for V3

### ISSUE THREAD

**Issue by rodrigoctoledo** [Azure/Azure-Media-Services-Explorer#130]
hi,
I currently use AMSE (Azure Media Service Explorer) V2 to manage my videos.
 Recently I received the message that on 01/01/2020 the AMS API will be migrated to V3. 
The behavior of the AMSE V3 tool is not the same as Asset management.
I really need to know what the impact will be on 01/01/2020, please.
will we have change in AMSE or AMS V2 / V3 API?

**Comment by rodrigoctoledo** [comment]
Will V2 be shut down?

**Comment by xpouyat** [comment]
Hello,
Where did you see that v2 will be deprecated? To my knowledge, therevis no such announcement. But it is true that some v2 processors will be deprecated and in some cases v3 provides a way to get the feature back. See https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-release-notes

**Comment by johndeu** [comment]
Rodrigo, 
We are actively working with customers to migrate them forward to the new ARM based v3 API.  We have not shut down the v2 API at all.  We have not even announced it yet. When I do get to announcing it, the goal will be to have as much feature parity or ability to migrate forward to new solutions as easily as possible.   You will have a lot of warning and ample time. 
Meanwhile, I would really want to know if there are any specific scenarios or use cases that prevent you from moving to v3 today.  Lets discuss that if possible.  That helps us to prioritize feature gaps.

**Comment by rodrigoctoledo** [comment]
Hi
Yes, we have a client here in Brazil that has a very high video demand per day, he was used to using the V2 process to create a .ttml video transcript and generate a multiple format encoding via link manifest.
V3's new process is more complicated than v2 and therefore complicates planning time and the process has some complications, for example, the name is the automatically generated asset, not the original file name, as in v2.
Could we make a call to clarify the process and we pass it on to the customer?
The customer is concerned because this activity is very important to their final work.
Thank You

**Comment by johndeu** [comment]
Sure thing, we can setup a call in the new year.  Ping me at amshelp@microsoft.com with the scenario and I'll loop in the right folks to discuss. 

We have ways to get the TTML (IMSC1) output in the V3 API, and will be making that easier in the new year. 
I'm not sure i followed your explanation of "multiple format encoding via link manifest"? Can you explain that part a bit more for me?
V3 Assets are now tracked ARM entities, so the name has to be unique per the rules of Azure Resources.  That's the way all Azure entities work now. If you need to preserve the original file name, we recommend dropping that into the Description, or the AlternateID fields - or tracking the metadata someplace externally as well -mapped to Asset ID or Asset unique name now in ARM. 
Also have the original file names in the asset name is complicated, as most file naming conventions do not follow the typical rules for naming things that show up on a URL.  You have to worry about URL encoding, removing some unicode character ranges, and following all the multiple RFC's for how to name something on a URL - which gets complicated if you dont have a URL encoding library ahead of creating the names.  So, again, best to use simpler names of GUIDs for the Asset unique name now in v3 and track file names in description field, or externally CMS mappings.

**Comment by rodrigoctoledo** [comment]
Hi, happy new year.

We need to put this file in V3, which v2 was compatible with:

  "Version": 1.0,
  "Codecs": [
    {
      "KeyFrameInterval": "00:00:02",
      "H264Layers": [
        {
          "Profile": "Auto",
          "Level": "auto",
          "Bitrate": 1000,
          "MaxBitrate": 1000,
          "BufferWindow": "00:00:05",
          "Width": 1080,
          "Height": 720,
          "BFrames": 3,
          "ReferenceFrames": 3,
          "AdaptiveBFrame": true,
          "Type": "H264Layer",
          "FrameRate": "0/1"
        },
        {
          "Profile": "Auto",
          "Level": "auto",
          "Bitrate": 750,
          "MaxBitrate": 750,
          "BufferWindow": "00:00:05",
          "Width": 720,
          "Height": 480,
          "BFrames": 3,
          "ReferenceFrames": 3,
          "AdaptiveBFrame": true,
          "Type": "H264Layer",
          "FrameRate": "0/1"
        },
        {
          "Profile": "Auto",
          "Level": "auto",
          "Bitrate": 500,
          "MaxBitrate": 500,
          "BufferWindow": "00:00:05",
          "Width": 540,
          "Height": 360,
          "BFrames": 3,
          "ReferenceFrames": 3,
          "AdaptiveBFrame": true,
          "Type": "H264Layer",
          "FrameRate": "0/1"
        },
        {
          "Profile": "Auto",
          "Level": "auto",
          "Bitrate": 200,
          "MaxBitrate": 200,
          "BufferWindow": "00:00:05",
          "Width": 360,
          "Height": 240,
          "BFrames": 3,
          "ReferenceFrames": 3,
          "AdaptiveBFrame": true,
          "Type": "H264Layer",
          "FrameRate": "0/1"
        }
        
        ],
      "Type": "H264Video"
    },
    {
      "Profile": "AACLC",
      "Channels": 1,
      "SamplingRate": 48000,
      "Bitrate": 64,
      "Type": "AACAudio"
    }
  ],
  "Outputs": [
    {
      "FileName": "{Basename}_{Width}x{Height}_{VideoBitrate}.mp4",
      "Format": {
        "Type": "MP4Format"
      }
    }
  ]
}

**Comment by rodrigoctoledo** [comment]
The name generated by the process of subtitling and encoding of the videos could be: "original_name_video - title"?
Because the customer needs to do batch operations, and if the name were this way automatic, would enable the use of the tool.
At the moment the tool requires that we define a new name for the process.

**Comment by xpouyat** [comment]
Hi, Regarding the encoding preset, I think the easier for you would be to create a custom transform with Azure CLI and import your customer preset. See https://docs.microsoft.com/en-us/azure/media-services/latest/custom-preset-cli-howto

**Comment by xpouyat** [comment]
> The name generated by the process of subtitling and encoding of the videos could be: "original_name_video - title"?
> Because the customer needs to do batch operations, and if the name were this way automatic, would enable the use of the tool.
> At the moment the tool requires that we define a new name for the process.

Which name is it ? Asset name ? Are you talking about the generated asset by the job ? Please provide more details.....

**Comment by rodrigoctoledo** [comment]
I refer to the name given by the subtitle process
![image](https://user-images.githubusercontent.com/29310960/71826022-c60be380-307b-11ea-834e-289a17ea1c39.png)
Can the name be a derivation of the original name with a "- subtitle"?

the batch process it is impossible
![image](https://user-images.githubusercontent.com/29310960/71826225-3581d300-307c-11ea-8dfb-adac5dfea8ea.png)

**Comment by xpouyat** [comment]
You have at least 3 names in you screenshots.
- transform name "defined_name" - I assume that some script/code created this name
- the job name : AMSE generates it automatically using the transform name and a unique short GUID
- the output asset name is based on the source asset + the job name

Today, when you submit the job, you cannot define the name of the output asset in the UI. This is because potentially, a transform could have one or several output assets... What you can do today with AMSE, is to create an empty asset with the name that you want, and specify this empty asset when creating the job (using "output asset" tab). 

![image](https://user-images.githubusercontent.com/8104205/71826733-e26d4780-309e-11ea-840f-b01dc05fdfeb.png)

**Comment by rodrigoctoledo** [comment]
Not possible, leave the name automatic?
from original file name

**Comment by xpouyat** [comment]
Today, the output asset name is automatic and is source asset + the job name (and job name is unique).
This ensure the asset name is unique.
Please take in account that an end user may submit multiple job for the same source asset and transform. That's why the output asset name must be unique by using a random GUID at some point.
I can add an option in the job / Output Asset UI to specify the output asset name rules and make the field editable.

**Comment by rodrigoctoledo** [comment]
It will help us a lot,

thank you very much: D

**Comment by rodrigoctoledo** [comment]
the email is coming back, did something happen? amshelp@microsoft.com

**Comment by xpouyat** [comment]
Next version will have this option:
![image](https://user-images.githubusercontent.com/8104205/71835121-19e4ef80-30b1-11ea-8f8b-665a69bf71d9.png)
