### ISSUE TITLE
AMSE sometimes uses an incorrect encryption key when creating test tokens

### ISSUE THREAD

**Issue by multiplexer2** [Azure/Azure-Media-Services-Explorer#132]
It always grabs the content key that happens to be the first one in the list. That's not always the correct one ... 

https://github.com/Azure/Azure-Media-Services-Explorer/blob/f7ea97becdccce5c5a4867c288a7a18e2e66b6af/AMSExplorer/AssetInformation.cs#L2030

**Comment by xpouyat** [comment]
Thanks for you comment. The next version of AMSE will solve this.

**Comment by xpouyat** [comment]
Solved in https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.2.0.2
