### ISSUE TITLE
Menu EXPORT

### ISSUE THREAD

**Issue by ASCA-BR** [Azure/Azure-Media-Services-Explorer#133]
Guys,  does someone know how to make available the option Export on the menu Asset in the version AMSE for V3  5.0.16.0? In the previous version (4.3.13.0) this option was available.
Thanks

**Comment by xpouyat** [comment]
Hello,
It needs to be re-implemented. Are you looking for the same features than in version 4.x ?
What is your scenario ?
Thanks

**Comment by xpouyat** [comment]
Can you provide me more details on what feature you want ? Export to Excel, copy to another AMS account, or export to another storage ?

**Comment by xpouyat** [comment]
Implemented in this release https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.2.1.0
