### ISSUE TITLE
Live Output's Created field is constantly changing

### ISSUE THREAD

**Issue by aregaz** [Azure/Azure-Media-Services-Explorer#134]
During the live stream, Live Output's **Created** field is constantly changing and always equal to **Last Modified** field.

I see the same behavior in SDK, so it might be the problem of SDK/API itself and not particularly AMSE related, but I can't find a proper place to report the bug.

**Comment by xpouyat** [comment]
Hello,
Yes, I don't think this is related to AMSE.
My recommendation is to create a support request in the Azure portal.
