### ISSUE TITLE
JOB Report is not avaliable in v3

### ISSUE THREAD

**Issue by ddixon1** [Azure/Azure-Media-Services-Explorer#136]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue concerns: (mark with an `x`)
```
- [ ] AMSE v4.x (for AMS v2)
- [X ] AMSE v5.x (for AMS v3)
```

### This issue is for a: (mark with an `x`)
```
- [x ] bug report
- [ ] UI issue report
- [ ] feature request
- [ ] performance problem
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. Select Transforms $ jobs tab
2. in the Jobs section highlight a job
3. right mouse click the job to open context menu
4. select Job report from the menu
* Job report selection is not selectable 

### Any log messages given by the failure
>None
### Expected/desired behavior
>expect to be able to view a job report as in v2
### OS and Version?
> Windows 7, 8 or 10.
Windows 10
### Versions
>

### Mention any other details that might be useful
This same process works fine in v2
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
![JobReport](https://user-images.githubusercontent.com/67067452/84926046-cf709180-b098-11ea-8eed-5178b735ad27.png)

**Comment by xpouyat** [comment]
Hi, it will be in the next release : transform report and job report.

**Comment by xpouyat** [comment]
In https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.4.3.0
