### ISSUE TITLE
Cannot Trim Asset as the duration is incorrect

### ISSUE THREAD

**Issue by jachin84** [Azure/Azure-Media-Services-Explorer#138]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue concerns: (mark with an `x`)
```
- [ ] AMSE v4.x (for AMS v2)
- [x] AMSE v5.x (for AMS v3)
```

### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] UI issue report
- [ ] feature request
- [ ] performance problem
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I am using the asset and locator defined [here](https://lampstandstreaming-aueas.streaming.media.azure.net/c66515ac-f34a-4073-abc5-556bb63ff53a/SundayMorning.ism/manifest). When attempting to create a filter the video is only 1min 14 in length when in fact the video is almost 2 hours long. 
![image](https://user-images.githubusercontent.com/2740855/92318489-5574f680-f050-11ea-9eab-fee30beb4943.png)

![image](https://user-images.githubusercontent.com/2740855/92318485-4d1cbb80-f050-11ea-87d6-8cda75f2cc7c.png) 
This prevents me from being able to set a startTime filter at 35mins. I believe the timescale for this clip is 1000 not 90000.
 

### Any log messages given by the failure
> N/A

### Expected/desired behavior
>The video length shows as the correct length enabling me to create a filter at the correct time.

### OS and Version?
> Windows 10.

### Versions
>Windows 2004 (19041.450)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by xpouyat** [comment]
Thanks for your bug report. I am looking into it.

**Comment by xpouyat** [comment]
I found a bug in how the duration is calculated. I fixed it and will push a new version of AMSE (after some tests).

**Comment by xpouyat** [comment]
Fixes : https://github.com/Azure/Azure-Media-Services-Explorer/commit/a5746e05038d6a31545e05de63079c09130d114d
New release : https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.2.0.7
This should solve the problem. Let me know if not.

**Comment by xpouyat** [comment]
Closing the issue. Reopen it or create a new one if the issue persists. Thanks
