### ISSUE TITLE
t

### ISSUE THREAD

**Issue by sameh2222222** [Azure/Azure-Media-Services-Explorer#139]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue concerns: (mark with an `x`)
```
- [ ] AMSE v4.x (for AMS v2)
- [ ] AMSE v5.x (for AMS v3)
```

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] UI issue report
- [ ] feature request
- [ ] performance problem
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10.

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by xpouyat** [comment]
Closing as it looks like an empty issue
