### ISSUE TITLE
videoUrl: Value isn't valid absolute URL of https scheme

### ISSUE THREAD

**Issue by swtimd79sv** [Azure/Azure-Media-Services-Explorer#140]
get this error while trying to upload video from the video indexer complete API reference guide.
I was able to establish connection and get the access token.

The url is a public url, that I have confirmed via python code as valid and absolute

The url is as below.
http://x-default-stgec.uplynk.com/ause/slices/773/34d28c6069b34f1d96307c80809697d7/77391df4befe487088bdc4fd05b204dd/77391df4befe487088bdc4fd05b204dd_g.mp4

**Comment by xpouyat** [comment]
Hello,
Is your issue with Video Indexer or Azure Media Services Explorer (AMSE) ?

With AMSE, I was able to import your URL and an asset was successfuly created.
To be able to use your link with a Video analysis task from a transform, I had to use the https schema, as it appears http is not supported. I talking about the "Create job from transform using http source" feature.

**Comment by swtimd79sv** [comment]
Hello, thanks for your response. Yes, I was trying this on AMSE and also with python. Turns out it did not like the http schema and I had to use https schema. It then accepted the url.  Yes, so your answer is right on track :)

**Comment by xpouyat** [comment]
Great. I updated the AMSE UI regarding the mandatory use of Https. It will be in next release.
