### ISSUE TITLE
Import from Azure always disabled.

### ISSUE THREAD

**Issue by MarvinPT** [Azure/Azure-Media-Services-Explorer#141]
Hello,

I'm trying to import some assets directly from azure blobs, but the Import from Azure is always disabled. I've tried as well with SAS link but that gives me an error that Requested URI does not represent a resource on the server. I'm sure that the resource exists as I've used AZ copy successfuly to send it to other accounts. 

I've tried attaching other storages, to no avail. 

Keep in mind that this might not be an error or bug, but I can't find no documentation explaining on how to create assets based on blobs already in storage so I'm a bit lost.

I have an AMS  V3 account without Classic API and I also have an AMS V3 account with Classic API both with the same behaviour. 

I'm trying to import via AMSE as I have hundreds of large files coming in via Blob and it would be great to process them without the redundant download/upload time. 

Thank you in advance

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue concerns: (mark with an `x`)
```
- [ ] AMSE v4.x (for AMS v2)
- [ x] AMSE v5.x (for AMS v3)
```

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ x] UI issue report
- [ ] feature request
- [ ] performance problem
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Asset => Import 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10.

### Versions
>

### Mention any other details that might be useful
![image](https://user-images.githubusercontent.com/4395898/108224607-fead3600-7132-11eb-8062-02fb1fe3eb71.png)
![image](https://user-images.githubusercontent.com/4395898/108225095-8004c880-7133-11eb-99b9-6b38788588fa.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by xpouyat** [comment]
Thanks for the report. This feature was in AMSE v4 and was not ported back to AMSE v5 yet.

The  feature "Import / From Azure Storage (SAS Container Path)" may be helpful. It imports all blobs from a specific Azure Storage Container.
You just need to create a Container SAS Url for example with Storage Explorer on that container :
![2021-02-22_16h11_19](https://user-images.githubusercontent.com/8104205/108727241-a4dcaf80-7528-11eb-9535-15b1fdcfb383.png)
Obviously, the blobs will be copied to one of the storage accounts attached to AMS account.
If the same storage account is used for the source and the destination, copy should be instantaneous.

Another option, if your asset contains only one blob, is to use "Import/From a single HTTP/HTTPS Url". You can pass a blob SAS URL with this feature.

Finally, another option is to create an empty asset with AMSE. You can control the container name at this step.
![2021-02-22_16h16_58](https://user-images.githubusercontent.com/8104205/108727979-65629300-7529-11eb-88bc-8425dff0b6ab.png)
Then you can use Azure Storage Explorer or AZCopy to copy blobs into that container.

Please let me know what you think of these options. The "import from Azure Storage" can be ported back to AMSE v5 but would require significant work to support ADAL authentication.

**Comment by MarvinPT** [comment]
> Thanks for the report. This feature was in AMSE v4 and was not ported back to AMSE v5 yet.
> 
> The feature "Import / From Azure Storage (SAS Container Path)" may be helpful. It imports all blobs from a specific Azure Storage Container.
> You just need to create a Container SAS Url for example with Storage Explorer on that container :
> ![2021-02-22_16h11_19](https://user-images.githubusercontent.com/8104205/108727241-a4dcaf80-7528-11eb-9535-15b1fdcfb383.png)
> Obviously, the blobs will be copied to one of the storage accounts attached to AMS account.
> If the same storage account is used for the source and the destination, copy should be instantaneous.
> 
> Another option, if your asset contains only one blob, is to use "Import/From a single HTTP/HTTPS Url". You can pass a blob SAS URL with this feature.
> 
> Finally, another option is to create an empty asset with AMSE. You can control the container name at this step.
> ![2021-02-22_16h16_58](https://user-images.githubusercontent.com/8104205/108727979-65629300-7529-11eb-88bc-8425dff0b6ab.png)
> Then you can use Azure Storage Explorer or AZCopy to copy blobs into that container.
> 
> Please let me know what you think of these options. The "import from Azure Storage" can be ported back to AMSE v5 but would require significant work to support ADAL authentication.

Thank you for the reply! This solves my problem, I now understand how the "Import / From Azure Storage (SAS Container Path)" should work, and even the single Https url is a great way to create assets on the fly. 

With these options available I see no need to port the feature.
