### ISSUE TITLE
Can not pick-up account by my personal azure account.

### ISSUE THREAD

**Issue by supershowwei** [Azure/Azure-Media-Services-Explorer#152]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue concerns: (mark with an `x`)
```
- [ ] AMSE v4.x (for AMS v2)
- [x] AMSE v5.x (for AMS v3)
```

### This issue is for a: (mark with an `x`)
```
- [x] bug report
- [ ] UI issue report
- [ ] feature request
- [ ] performance problem
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Click 'Pick-up / create an account...'
> Check 'Select or create an account by browsing your tenants & subscriptions'
> Input my personal azure account.

### Any log messages given by the failure
> 'xxx is not in our system.'

### Expected/desired behavior
> Show my subscriptions and Azure Media Service accounts.

### OS and Version?
> Windows 10.

### Versions
> 5.4.7.0 for Media Services v3

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Works fine when i downgrade to 5.3.0.1 (for AMS v3).

**Comment by xpouyat** [comment]
Hello,
Did you try to "force user selection" ?
![2022-02-09_15h45_57](https://user-images.githubusercontent.com/8104205/153225049-7ed94ca6-b601-4599-b6bf-12773cf716f0.png)

**Comment by supershowwei** [comment]
> Hello, Did you try to "force user selection" ? ![2022-02-09_15h45_57](https://user-images.githubusercontent.com/8104205/153225049-7ed94ca6-b601-4599-b6bf-12773cf716f0.png)

yes, i tried.

**Comment by supershowwei** [comment]
I signed up for Azure using my personal account. What will be my organization information?

**Comment by xpouyat** [comment]
Ah, not sure you can use this organization option in that case.
I just released a new version of the tool with updated packages for authentication. You may try...

**Comment by xpouyat** [comment]
Hello,
I was expecting thigs to be better by using [WAM in this release](https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.7.0.0), but it looks like [personal account cannot be easily used with this library](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4010) to connect to Azure.

**Comment by xpouyat** [comment]
Closing as MSA account cannot be used.
