### ISSUE TITLE
how to download video from azure media ?

### ISSUE THREAD

**Issue by muhamedadeM** [Azure/Azure-Media-Services-Explorer#159]
just lik this link below
i need to downlow video from it 

[https://almen-almentormedia-euno.streaming.media.azure.net/b2253229-2e25-4502-a96e-d5c2a3ac6b3a/main.ism/manifest(format=mpd-time-cmaf,encryption=cenc)](url)

**Comment by xpouyat** [comment]
Hello,
If you have access to the Media Services Account then you can download the file using AMS API or AMSE.
If you don't have access then I cannot help you as the stream above is DRM protected.
Regards,
