### ISSUE TITLE
Add to WinGet

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [Azure/Azure-Media-Services-Explorer#161]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue concerns: (mark with an `x`)
```
- [ ] AMSE v4.x (for AMS v2)
- [x] AMSE v5.x (for AMS v3)
```

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] UI issue report
- [x] feature request
- [ ] performance problem
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 

### Any log messages given by the failure
>

### Expected/desired behavior
> Would like to able to download the software via WinGet

### OS and Version?
> Windows 7, 8 or 10.

### Versions
> Any

### Mention any other details that might be useful
This was recently done on a different Azure Repo here via a Pull Request Action to be able to automate this as part of the release cycle of Azure Media Services Explorer - https://github.com/Azure/aztfy/pull/254/files 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by xpouyat** [comment]
Hello, thanks for the suggestion. I am looking to it.

**Comment by xpouyat** [comment]
It's done. Try:
winget install Microsoft.AzureMediaServicesExplorer

**Comment by andrew-flatters-bliss** [comment]
Great stuff - just tested it on my machine and seems to be working cheers!

**Comment by xpouyat** [comment]
Yep. But it does not install .Net 6 runtime. I did not find a way to declare a dependency on another winget package.
If .Net 6 runtime is not installed, AMSE proposes to download it at runtime anyway.

**Comment by andrew-flatters-bliss** [comment]
Just looking at the manifest this could be something that's coming - assuming for this could use `PackageDependencies` which seems to be the only one in Experimental at moment 

```
 Dependencies:               # *Experimental* list of dependencies required by the package
      - ExternalDependencies:   # *Not implemented* list of external dependencies
        PackageDependencies:    # *Experimental* list of package dependencies
        WindowsFeatures:        # *Not implemented* list of Windows feature dependencies
        WindowsLibraries:       # *Not implemented* list of Windows library dependencies
```

https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.2.0/installer.md#installer-manifest

**Comment by xpouyat** [comment]
Correct, it looks like it's doable
https://github.com/microsoft/winget-cli/issues/163

**Comment by xpouyat** [comment]
The experimental feature just displays the dependencies for now. I added the install commands in the main readme.
https://github.com/Azure/Azure-Media-Services-Explorer/blob/main/README.md#installing-the-tool-with-winget
