### ISSUE TITLE
cannot add rateControlMode in custom preset

### ISSUE THREAD

**Issue by sudonghan** [Azure/Azure-Media-Services-Explorer#162]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue concerns: (mark with an `x`)
```
- [ ] AMSE v4.x (for AMS v2)
- [ ] AMSE v5.x (for AMS v3)
```

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] UI issue report
- [ ] feature request
- [ ] performance problem
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I want to customize the preset and added the rateControlMode 

### Any log messages given by the failure
>The property 'rateControlMode' does not exist on type 'Microsoft.Media.H264Video'. Make sure to only use property names that are defined by the type.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10.

### Versions
>

### Mention any other details that might be useful
I catched the network trace using fiddler and find that the failure is due to the API is using an old version.
but rateControlMode is supported in 2021-11-01.
So I tested with the new REST API version and it worked.
https://learn.microsoft.com/en-us/rest/api/media/transforms/create-or-update?tabs=HTTP#h264ratecontrolmode
release notes:
https://learn.microsoft.com/en-us/azure/media-services/latest/release-notes#march-2022

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by xpouyat** [comment]
Hello,
Good catch. The custom preset in AMSE uses REST calls tagged with "2020-05-01". I will update the code to use "2021-11-01".

**Comment by xpouyat** [comment]
This should be fixed in that release https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.6.1.0
