### ISSUE TITLE
Open Source Backend Components

### ISSUE THREAD

**Issue by jachin84** [Azure/Azure-Media-Services-Explorer#168]
With Azure Media Service being retired is there any chance that MS will open-source any of the backend components of the AMS solution?

**Comment by xpouyat** [comment]
Hi jachin84,
Microsoft did not announce such plan.
For AMSE, my plan is to add support for migration of assets to MK/IO. There is a private branch for that. I will release a version when I will have something stable.
A tool to migrate assets to Azure Storage with static packaging is also available.
