### ISSUE TITLE
[Indexer] Remove warning for special characters

### ISSUE THREAD

**Issue by asolanki** [Azure/Azure-Media-Services-Explorer#32]
Previous versions of Azure Media Indexer were restricted to plain ASCII symbols in filename.  

The current version can now support Unicode.  Warning should be removed from Indexer dialog.

**Comment by asolanki** [comment]
![image](https://cloud.githubusercontent.com/assets/1024909/5730696/64e4affe-9b31-11e4-8f22-4dc33d5206bb.png)

**Comment by xpouyat** [comment]
Thanks for the note. Yes, this warning has been removed recently
https://github.com/Azure/Azure-Media-Services-Explorer/commit/c31bac19444476bef153450568793a4d573ec226

**Comment by asolanki** [comment]
Ah, I was on an older build!  That explains why I looked for 30 minutes through the source code for the warning, and couldn't find it :) :+1:

**Comment by xpouyat** [comment]
☺
Yes, I removed the code when I saw an email saying that Indexer does not have this issue anymore.
Please update me when there are other changes in Indexer.


-          Xavier
