### ISSUE TITLE
Feature Ask: Proxy server configuration

### ISSUE THREAD

**Issue by kesder** [Azure/Azure-Media-Services-Explorer#45]
It would be great if connections through proxy servers could be configured at startup.

**Comment by xpouyat** [comment]
Hello,
Can you explain this request with more details? Thanks

**Comment by kesder** [comment]
Actually - as far as I can see - the Explorer cannot connect to Azure Media Services in case the client has to use a proxy server to connect to the internet. So it would be great to offer something like a general settings dialog allowing configuration of a proxy server (address, port, username, password).

**Comment by xpouyat** [comment]
I think that Explorer uses automatic Proxy detection provided by .NET. https://msdn.microsoft.com/en-us/library/fze2ytx2(v=vs.110).aspx
Did you configure your Proxy using the Internet Explorer Local Area Network (LAN) dialog box ?

**Comment by xpouyat** [comment]
Try also to add your proxy settings in "C:\Program Files (x86)\Microsoft Corporation\Azure Media Services Explorer\AMSExplorer.exe.config" as described in
https://social.msdn.microsoft.com/Forums/azure/en-US/19fab84a-e0a9-4a54-96a0-6fd140a74e69/how-to-connect-to-http-proxy-using-azure-sdk

**Comment by kesder** [comment]
Thank you for the hints, but it didn't work for me without the possibility to explicitly specify credentials. There is an interesting solution using a custom proxy implementation which allows setting user name and password in the AMSExplorer.exe.config: http://lastattacker.blogspot.de/2011/06/configuring-proxy-settings-in-net.html - unfortunately I didn't make it work. ;-) I created the dll, put it into the explorer's root folder and configured AMSExplorer.exe.config accordingly. Apparently it still doesn't find my dll or has problems with it or anything - I am not familiar with dll's and c# programming but I guess others would easily make it work. Maybe it's also a nice feature for the official AMSExplorer release?

**Comment by xpouyat** [comment]
Closing. Please reopen an issue if you still hit the problem.
