### ISSUE TITLE
Bulk upload doesn't respect bulk container name with Signiant

### ISSUE THREAD

**Issue by sabbour** [Azure/Azure-Media-Services-Explorer#50]
When creating a bulk upload request, the generated Signiant CLI command line assumes uploading in **manifest-GUID** container, in disregard to what was specified in the interface.

**Comment by xpouyat** [comment]
Hi Ahmed,
Yes, this is expected. When you say "in disregard to what specified in the interface", what do you mean?
The bulk ingest mechanism is like a "watch folder" using an Azure storage container. When the file arrived into the manifest-GUID container, AMS creates the asset and move the file to the asset container.

**Comment by sabbour** [comment]
What happened is that after Signiant CLI uploaded into manifest-GUID folder, AMS never kicked in and packaged the incoming assets. The asset-GUID folder had 0 byte references to the mp4 files.

<img width="598" alt="ingest" src="https://cloud.githubusercontent.com/assets/103856/12993944/2095923c-d0d2-11e5-9133-c824aa6c7d52.PNG">
The highlighted field is a bit confusing

**Comment by xpouyat** [comment]
I see. The "bulk ingest container name" is confusing. I will rename it to "Bulk batch name" or "Bulk name". It does not impact the real container name. It can be used by the user to remember the purpose of the bulk upload. For example, "Feb 12 upload", or "Serie XY upload".

Regarding 0 byte reference, I know there could be an issue with Bulk and Signiant. In some cases like a network disconnection, Signiant creates a file of 0 byte and then update the size when upload is complete. The 0 size file is processed by AMS which thinks that upload is complete as the file is there. This is probably what you experience. Please confirm.
