### ISSUE TITLE
Generate a manifest function generates a wrong manifest

### ISSUE THREAD

**Issue by chlela** [Azure/Azure-Media-Services-Explorer#51]
Audio files are marked as video and one of the video files is marked as an audio. Here's an example of a manifest generated by Azure Media Services encoder

`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<smil xmlns="http://www.w3.org/2001/SMIL20/Language">
  <head>
    <meta name="formats" content="mp4" />
  </head>
  <body>
    <switch>
      <video src="4582_H264_6000kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4582_H264_4700kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4582_H264_3400kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4582_H264_2250kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4582_H264_1500kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4582_H264_1000kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4582_H264_650kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4582_H264_400kbps_AAC_und_ch2_128kbps.mp4" />
      <audio src="4582_AAC_und_ch2_128kbps.mp4" title="AAC_und_ch2_128kbps" />
      <audio src="4582_AAC_und_ch2_56kbps.mp4" title="AAC_und_ch2_56kbps" />
    </switch>
  </body>
</smil>`

Here's an example of a manifest generated by the explorer

`<?xml version="1.0" encoding="utf-8" standalone="yes"?><smil xmlns="http://www.w3.org/2001/SMIL20/Language">
  <head>
    <meta name="formats" content="mp4" />
  </head>
  <body>
    <switch>
      <video src="4603_H264_650kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4603_H264_6000kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4603_H264_4700kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4603_H264_400kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4603_H264_3400kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4603_H264_2250kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4603_H264_1500kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4603_H264_1000kbps_AAC_und_ch2_128kbps.mp4" />
      <video src="4603_AAC_und_ch2_56kbps.mp4" />
      <video src="4603_AAC_und_ch2_128kbps.mp4" />
      <audio src="4603_H264_650kbps_AAC_und_ch2_128kbps.mp4" title="audioname" />
    </switch>
  </body>
</smil>`

**Comment by xpouyat** [comment]
Hello Guy,
Thanks for the feedback. It is true that when AMS Explorer generates a manifest, the assumption is that all the mp4 files contains video. It tries to guess which file is the best for the audio track (by looking to the file name). As it is just guess, the manifest is displayed so the end user can edit it and make the corrections.
Can you explain your scenario ? If you use Media Encoder Standard, you don't need to generate a manifest as it is already generated by the encoder.

**Comment by chlela** [comment]
Hi Xavier,
I agree that the .mp4 is a video file extension and it is misleading from the Media Services encoder.  I noticed that the audio files don't contain H264 in the file name, which could be a better way to guess the audio file names for the h264 task presets. it would be nice to get a list of generated file names from the media services team to create a better guessing method for all other presets like "VC1 and WMA"

My scenario is that I'm migrating media services accounts, I wrote a script to migrate the blob storage account and for some reason some of the manifest files were empty so I manually used the explorer to generate them.

**Comment by xpouyat** [comment]
Oh I see. That is strange that the manifests are empty.
The generate manifest feature is mainly used by customers that have already encoded assets (encoded by a third party encoder). So the code have no clue about the naming conventions used in that case...

**Comment by chlela** [comment]
I suggest a bigger, bolder message stating that the explorer is guessing the manifest structure.  

I still feel that there is a bug because one of the mp4 files was marked as an audio file `<audio src="4603_H264_650kbps_AAC_und_ch2_128kbps.mp4" title="audioname" />`

**Comment by xpouyat** [comment]
Thanks for the feedback. I will add a message.
I will look to improve the audio mp4 file detection by using the file size.
