### ISSUE TITLE
ffmpeg RTP streaming

### ISSUE THREAD

**Issue by skaya129** [Azure/Azure-Media-Services-Explorer#52]
Hi,

I can't stream to AMS over rtp with the ffmpeg command in the app. What could be wrong?

**Comment by skaya129** [comment]
I found a way, ffmpeg command must be finished with : 

-f mpegts udp://xxxxxx.rtp.channel.mediaservices.windows.net:2010?pkt_size=1316

**Comment by ThadeuFerreira** [comment]
Hello.

What is the full command for FFMPEG? And how should I configure the Azure Media Service?

**Comment by skaya129** [comment]
Hi,

On Azure Portal you create a channel with these settings : 
Encoding type : live encoding
Streaming Protocol : RTP/MPEG-2 Transport Streaming
Video Stream Selection : 0
Audio Stream Selection : 0

and the ffmpeg command is :  DONT'FORGET to change the ingest url, you replace the "rtp://" with "udp://"

ffmpeg  -i your_input_src -strict -2 -c:a aac -b:a 96k -ar 44100 -r 30 -g 60 -keyint_min 60 -b:v 800000 -c:v libx264 -preset medium -bufsize 800k -maxrate 800k -threads 0 -f mpegts udp://xxxxxxx.rtp.channel.mediaservices.windows.net:2010/?pkt_size=1316

**Comment by xpouyat** [comment]
RTP/MPEG-2 is going to be removed from AMS this month
