### ISSUE TITLE
Error : MediaProcessor : A fragment is too long, possibly because a subset of the input tracks is not aligned

### ISSUE THREAD

**Issue by hahaxj** [Azure/Azure-Media-Services-Explorer#53]
After uploading multi file to media service, we need  validating adaptive bitrate MP4s for static package. But during validating, we get error: [7/22/2016 7:30:30 PM] Task 'Validate Multi MP4 of testmedia', Error : MediaProcessor : A fragment is too long, possibly because a subset of the input tracks is not aligned.

But when we use other group files , it work well.

So why we get this error ? Is it about for the origin files ?

Thanks a lot.

James

**Comment by xpouyat** [comment]
Hello James,

You should create support request.
Go to the Azure Portal. Click on the interrogation mark (top left) and "New Support Request". Submit the support request with details.
Then please provide me the ticket ID.

Thanks

Xavier

**Comment by hahaxj** [comment]
Hi Xavier:

Thanks for your reply.
Now we use the China Azure, the ticket id is 2016072144038.
