### ISSUE TITLE
Cannot see preview windows on SubClip Form

### ISSUE THREAD

**Issue by hahaxj** [Azure/Azure-Media-Services-Explorer#54]
Based on https://azure.microsoft.com/en-us/blog/sub-clipping-and-live-archive-extraction-with-media-encoder-standard/, during subclipping, we cannot see the preview windows, but from the reference, we should see the Form(I have set the streaming endpoint for 1 unit).

Thanks a lot.
James

**Comment by xpouyat** [comment]
Hello James,
I identified a bug in the current version, when the asset has been already published. It will be corrected in the next public release. Let me know if you want to test a preview of this new version.
- Xavier

**Comment by xpouyat** [comment]
Hello,
Please check the new version on https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v3.43.0.0 and tell me if this fixes the issue or not.
Thanks!
