### ISSUE TITLE
Cannot login to AMSE after i upgraded to latest version

### ISSUE THREAD

**Issue by mmedhekar** [Azure/Azure-Media-Services-Explorer#56]
I updated AMSE to latest version on server 2012R2 and now i cannot login to my account. AMSE throws an error "An error occurred while executing this request, AMS explorer will exit."

**Comment by xpouyat** [comment]
Hello,
Do you have additional data displayed or just this message ?
It was working fine before the upgrade ?

**Comment by mmedhekar** [comment]
Hi Xavier,


I just see message included in the bug. Here is the snapshot of the error


[cid:6c5bb803-42ba-417b-a391-1b3243794d2b]


It could be related to recent windows update.

I had 3.45.0.0 previously which was working fine till last week. After OS updates were installed that version started throwing Null Reference exception on loading the UI. Here is the snapshot of error i was getting for version 3.45.0.0


[cid:33fc6ab7-c6d5-41ac-978c-5819251706d7]


Please let me know if you need anymore information from my side.


Thanks,

Mayur

________________________________

**Comment by xpouyat** [comment]
Hi, I don't see the screen captures. Can you send me them to amse @ Microsoft.com ?
Thanks

**Comment by xpouyat** [comment]
Issue solved.
