### ISSUE TITLE
Requested value 'Chinese Simplified' was not found.

### ISSUE THREAD

**Issue by shaqian** [Azure/Azure-Media-Services-Explorer#60]
Media Analytics > Video OCR request returns error:
Requested value 'Chinese Simplified' was not found.

The cause is ChineseSimplified should not have space. 

AMSExplorer/Forms-MediaAnalytics/MediaAnalyticsVideoOCR.cs 
        public readonly List<Item> VideOCRLanguages = new List<Item> {
            new Item("Undefined", ""),
            new Item("Arabic", "Arabic"),
            new Item("Chinese Simplified", "**ChineseSimplified**"),
            new Item("Chinese Traditional", "**ChineseTraditional**"),
            new Item("Czech", "Czech"),
            new Item("Danish", "Danish"),
            new Item("Dutch", "Dutch"),
            new Item("English", "English"),
            new Item("Finnish", "Finnish"),
            new Item("French", "French"),
            new Item("German", "German"),
            new Item("Greek", "Greek"),
            new Item("Hungarian", "Hungarian"),
            new Item("Italian", "Italian"),
            new Item("Japanese", "Japanese"),
            new Item("Korean", "Korean"),
            new Item("Norwegian", "Norwegian"),
            new Item("Polish", "Polish"),
            new Item("Portuguese", "Portuguese"),
            new Item("Romanian", "Romanian"),
            new Item("Russian", "Russian"),
            new Item("Serbian Cyrillic", "**SerbianCyrillic**"),
            new Item("Serbian Latin", "**SerbianLatin**"),
            new Item("Slovak", "Slovak"),
            new Item("Spanish", "Spanish"),
            new Item("Swedish", "Swedish"),
            new Item("Turkish", "Turkish")
        };

Reference: [Use Azure Media Analytics to convert text content in video files into digital text](https://docs.microsoft.com/en-us/azure/media-services/media-services-video-optical-character-recognition)

> Language	(optional) describes the language of text for which to look. One of the following: AutoDetect (default), Arabic, ChineseSimplified, ChineseTraditional, Czech Danish, Dutch, English, Finnish, French, German, Greek, Hungarian, Italian, Japanese, Korean, Norwegian, Polish, Portuguese, Romanian, Russian, SerbianCyrillic, SerbianLatin, Slovak, Spanish, Swedish, Turkish.

**Comment by xpouyat** [comment]
Thanks for the feedback. Update has been integrated in code and next public release will have it.

**Comment by xpouyat** [comment]
Fix is in v3.48.0.0.
Thanks.
