### ISSUE TITLE
Upload queue stuck when files to upload not found

### ISSUE THREAD

**Issue by otnaicus** [Azure/Azure-Media-Services-Explorer#62]
Deleting or moving the file or folder after queuing it for upload will cause AMS explorer to endlessly attempt locating the missing file or folder without any prompts.

Suggest implementing a time-out, or prompt user to skip/locate the file or folder.

**Comment by xpouyat** [comment]
Thanks for the feedback. I identified an issue in the way error was handled. Fix will be in the next public version.
