### ISSUE TITLE
First asset upload sometimes doesn't start

### ISSUE THREAD

**Issue by pollax** [Azure/Azure-Media-Services-Explorer#65]
Hi,
I often experience a problem uploading the first asset after starting the application. In the transfer window, the start time never appears. They only way to solve it is to cancel (and the cancel operation also never finishes) and then re-upload the same file again.

Scenario 1, single file asset:
1. Open application.
2. Connect to account.
3. Select to upload asset.
-> Transfer appears under Transfers tab, but it never starts.
If I cancel it, the cancel operation never finishes either.

Scenario 2, multiple files into multiple assets
1. Open application
2. Connect to account
3. Select to upload files in to separate assets.
-> The first transfer never starts, but the other ones do.
If I cancel the not starting transfer, the cancel operation never finishes either.

I'm on Windows 10 Pro.

**Comment by xpouyat** [comment]
Old issue. Please re open an issue if you have the issue with the current v5.x version. Thanks
