### ISSUE TITLE
The concurrent transfer limit is off by one when starting multiple transfers at once

### ISSUE THREAD

**Issue by pollax** [Azure/Azure-Media-Services-Explorer#67]
See attached screenshot for reference. Taken after adding multiple transfers (drag n' drop).
![amse-upload_limit](https://cloud.githubusercontent.com/assets/1932627/23396184/cc71ec0c-fd92-11e6-9019-a9aea489553d.PNG)

**Comment by xpouyat** [comment]
I don't see it this behavior in the latest version.
