### ISSUE TITLE
Docs not found

### ISSUE THREAD

**Issue by kiquenet** [Azure/Azure-Media-Services-Explorer#70]
https://docs.com/fukushima-shigeyuki/3439/english-azure-media-services-step-by-step-series not found

**Comment by shigeyf** [comment]
Thanks for your report.
Yes, I have realized that some problem is happening on my corporate docs.com account.
So I have uploaded my docs on to my personal account as below:
https://docs.com/shigeyf/1220/azure-media-services-step-by-step-tutorial-series
Please use this.
Thanks,
-Shige
