### ISSUE TITLE
Option to resume uploads?

### ISSUE THREAD

**Issue by hashcutdev** [Azure/Azure-Media-Services-Explorer#73]
Hello, I've been trying to upload large media files (20-30GB apiece) and if it fails in the middle, there's no option to resume the upload. I've seen articles that say this can be done programmatically. I was wondering if you've given thought to adding this functionality?

Conversely, is there a GUI-based azure uploader that has resume functionality?

AMSE is awesome at making it easy and simple to access all of Azure's media services. I think a resume feature would make it even better (especially given how big media files can be these days). Thank you!

**Comment by Misiu** [comment]
any updates on that?

**Comment by xpouyat** [comment]
Hello,
The new release https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.2.1.0 uses now the Azure Data Movement Library so you should have a better experience for uploads and downloads. Let me know.

**Comment by aerott** [comment]
@xpouyat - good news! It works well, but I don't see resume option. Maybe I can't find them or not yet existing.

**Comment by xpouyat** [comment]
There is no resume option.

**Comment by Misiu** [comment]
> There is no resume option.

Do you have plans to add this option?
I need to upload 4-hour videos in 4K resolution.  The average file size is around 40 GB per file.
So it would be a shame to have the upload crash at 99% :/

**Comment by xpouyat** [comment]
Thanks. I will investigate. The library has this feature. https://docs.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library#resume-a-canceled-transfer

**Comment by xpouyat** [comment]
It's developed. Next release will have it

**Comment by xpouyat** [comment]
It's there https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.4.3.0
