### ISSUE TITLE
Cannot change user to login

### ISSUE THREAD

**Issue by PoseyZhong** [Azure/Azure-Media-Services-Explorer#77]
When I use an unauthorized user to login, I got an 401 error. But I cannot change user to login again. I have to exit the application and open it again.

**Comment by m-otoguro** [comment]
I have same issue.

exception is thrown because Rest API returns 401 when "context.Assets.FirstOrDefault()" is called  at Line 352 in AMSLogin.cs.
There are no dialog before 401 is returned.
So I can't enter any account information.

**Comment by combined-knowledge** [comment]
I also have this issue, but restarting the application doesn't give me the opportunity to update credentials. 
In our case the Azure user's password has changed. 
Have tried: 
Removing and re-creating the Media Services account settings in the list
Uninstalling / reinstalling AMSE (ensuring any residual settings files have been removed - none found)
Clearing IE cache 

Thanks

**Comment by xpouyat** [comment]
This feature will be in the new v5 version for AMS v3
