### ISSUE TITLE
Embedded player in subclipping window doesn't play

### ISSUE THREAD

**Issue by dbristolms** [Azure/Azure-Media-Services-Explorer#78]
You get "Video playback aborted. (0x20100002)" when trying to preview the video in the subclipping window. AMSE video preview window uses the browser and calls the URL https://ampdemo.azureedge.net/azuremediaplayer_embed.html?autoplay=true&url={0} with the streaming URL replacing {0}.  If the streaming URL is HTTP this will fail since you cannot have mixed monikers of HTTP and HTTPS.

In Subclipping.cs in PlaybackAsset() the embedded player is called with PlayerType.AzureMediaPlayerFrame as the type of player.  In Program.cs in DoPlayBackWithStreamingEndpoint() the player type is detected:
                        else if (typeplayer == PlayerType.AzureMediaPlayerFrame)
                        {
                            playerurlbase = Constants.PlayerAMPIFrameToLaunch;
                        }

The string for PlayerAMPIFrameToLaunch is:
        public const string PlayerAMPIFrameToLaunch = @"https://ampdemo.azureedge.net/azuremediaplayer_embed.html?autoplay=true&url={0}";

So if the URL for the video is HTTP, this will conflict.  This seems to be handled in the next else if in DoPlayBackWithStreamingEndpoint():
                        else if (typeplayer == PlayerType.AzureMediaPlayerClear)
                        {
                            playerurlbase = Constants.PlayerAMPToLaunch.Replace("https://", "http://");
                        }

This could be probably most gracefully be handled by stripping of the moniker and colon completely.

**Comment by xpouyat** [comment]
Thanks for the report!
Recently, I switched the players to https but I forgot to move the locator URL to https in subclipper. This will be fixed in the next release. Commit https://github.com/Azure/Azure-Media-Services-Explorer/commit/0ccb656656c89d543dc410ce39be826e3975bb2e
