### ISSUE TITLE
The Locator URLs in "Asset report"

### ISSUE THREAD

**Issue by HAYAKAWATuyosi** [Azure/Azure-Media-Services-Explorer#81]
The Locator URLs shown in "Asset report" lose postfixes like "(format=...)" .

>Smooth Streaming URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest
>Smooth Streaming (legacy) URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest
>MPEG-DASH URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest
>HLS v4  URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest
>HLS v3  URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest

I think It should be below. Is not it?

>Smooth Streaming URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest
>Smooth Streaming (legacy) URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest(format=fmp4-v20)
>MPEG-DASH URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest(format=mpd-time-csf)
>HLS v4  URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest(format=m3u8-aapl)
>HLS v3  URL : 
>http://xxx.streaming.mediaservices.windows.net/yyy/zzz.ism/manifest(format=m3u8-aapl-v3)

**Comment by xpouyat** [comment]
Thanks for the report! I fixed the issue. It will be in the next release.
https://github.com/Azure/Azure-Media-Services-Explorer/commit/9255c771aa01177f81909f6033854548b31386db
