### ISSUE TITLE
Azure Media Services Explorer Mac version

### ISSUE THREAD

**Issue by horrion** [Azure/Azure-Media-Services-Explorer#83]
Please release a Mac version of this tool.

**Comment by Teides** [comment]
+5 Please

**Comment by DirkSW** [comment]
+10 Please

**Comment by azbiz** [comment]
+20 Please

**Comment by bernardoflynn** [comment]
are there any other tools that I can manage content in AMS on a mac?

**Comment by xpouyat** [comment]
The best for now is the Azure Portal.
