### ISSUE TITLE
Cannot delete assets since upgrading to 4.1.0.0

### ISSUE THREAD

**Issue by todthomson** [Azure/Azure-Media-Services-Explorer#84]
Hi Azure Media Services Explorer,

Just updated to 4.1.0.0 (after being prompted in-app) and I can no longer delete Assets completely via the Assets tab.

Has anyone else seen this? Presuming a regression/bug in the new release.

Thanks,

Tod.

**Comment by xpouyat** [comment]
Hi, I am looking to it. (Yes, code has been updated in the last version to better deal with Fairplay cryptography deletion.)

**Comment by xpouyat** [comment]
Fixed in release 4.1.1.0

**Comment by todthomson** [comment]
@xpouyat I can confirm that it's working again in 4.1.1.0 👍 thanks, I really appreciate the quick turn around on this one.
