### ISSUE TITLE
Readme.md points to deprecated site

### ISSUE THREAD

**Issue by sumitkm** [Azure/Azure-Media-Services-Explorer#85]
The URL "There are some nice [Azure Media Services Step-by-Step](https://docs.com/shigeyf/1220/azure-media-services-step-by-step-tutorial-series) tutorials using Azure Media Services Explorer." is pointing to a deprecated site. Kindly update it. 

It is difficult enough to find updated documentation on Azure Media Services, the repository pointing to deprecated sites makes it really frustrating.

**Comment by xpouyat** [comment]
This is fixed now. Thanks
