### ISSUE TITLE
Cannot import from storage account

### ISSUE THREAD

**Issue by hahaxj** [Azure/Azure-Media-Services-Explorer#88]
If we import from storage account , I get error as following:
The remote name could not be resolved: 'fornorthmedia.blob.chinacloudapi.cn'

How should we handle the exception ?

Thanks a lot.

**Comment by xpouyat** [comment]
Hi,
I will check the code. Looks like it should use blob.core.chinacloudapi.cn and not blob.chinacloudapi.cn

**Comment by xpouyat** [comment]
Hi, I sent you email with a private build that should correct the issue. Can you check the build and let me know if it solves your issue ?

**Comment by xpouyat** [comment]
Hello,
Any update ? Did you try the build ?
