### ISSUE TITLE
Content adaptive multi bitrate isn't compatible with prefragmented job options

### ISSUE THREAD

**Issue by simonsabin** [Azure/Azure-Media-Services-Explorer#89]
If I select the Content adaptive multi bitrate encoding and the job options are set to prefragment output assets you get an error saying that's not compatible. 

`Microsoft.Cloud.Media.Encoding.PresetException: Preset used, 'Content Adaptive Multiple Bitrate MP4' is not compatible with AssetFormatOption.AdaptiveStreaming set on the output Asset. Please use AssetFormatOption.None, or, use 'Adaptive Streaming' as the preset.`

But if I chose the H264 Multi bit rate and un check the "don't interlace option" I can use prefragmented as the output.

**Comment by xpouyat** [comment]
Thanks. I am checking with the product team....

**Comment by xpouyat** [comment]
So, this is expected. The 'Content Adaptive Multiple Bitrate MP4' preset interleaves audio and video in the standalone MP4 file. This preset is designed for MP4 files output. If you want pre-fragmented output, then you don't need this preset for M%P4 files ; you can use the 'Adaptive Streaming' preset which supports pre-fragmented output.
