### ISSUE TITLE
App resume keeps Folder watch running

### ISSUE THREAD

**Issue by gerhardcit** [Azure/Azure-Media-Services-Explorer#90]
Thx for this great app, it is a life saver.

Just a small thing. 
When the app resumes (after a remote desktop connection was re-established) and the ap was unresponsive for a while, the folder watch seems to be stuck (Ctrl-W)

Switching it off and on has no effect. The folder is still watched.
Restarting the app is the the only way to stop the watching then.

**Comment by xpouyat** [comment]
Folder watch was in previous version of AMSE, but not anymore in AMSE v5.
