### ISSUE TITLE
Got error prompt on  Visual Overlay page

### ISSUE THREAD

**Issue by chenxin21cn** [Azure/Azure-Media-Services-Explorer#91]
Hi,

For version 4.2.0.1, after I enable the "Overlay an image onto the video" and select an image file, I got the error  prompt: "Can not add Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JObject" . I have attached the screen capture for your reference.

Thanks
![image](https://user-images.githubusercontent.com/12132648/37705335-a72272c6-2d36-11e8-855d-c544d6ac5492.png)

**Comment by xpouyat** [comment]
Hi,
I found and fixed the bug. Fix will be in the next release. Let me know if you need a private build before.
Thanks

**Comment by xpouyat** [comment]
https://github.com/Azure/Azure-Media-Services-Explorer/commit/b4be6f5e3be432eccbd887b38dd28448b3542183
