### ISSUE TITLE
Broken readme link to tutorials

### ISSUE THREAD

**Issue by dcbrown16** [Azure/Azure-Media-Services-Explorer#92]
The link in the section of the readme below does not work for me - it gets redirected to www.office.com.
"There are some nice Azure Media Services Step-by-Step tutorials using Azure Media Services Explorer."
(https://docs.com/shigeyf/1220/azure-media-services-step-by-step-tutorial-series)

If these are still up, please relink. Thanks!

**Comment by rimi-itk** [comment]
I've just into this as well. In the release notes (https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v4.2.0.1) “some tutorials” points to http://aka.ms/amstutorials. Maybe that's what we're looking for …

@xpouyat, can you confirm this?

**Comment by xpouyat** [comment]
Hi,
I fixed the link in the readme (it was fixed in the release description.
Thanks!
