### ISSUE TITLE
Can't export to another azure media account

### ISSUE THREAD

**Issue by tcbjc** [Azure/Azure-Media-Services-Explorer#95]
We use Azure Media Services and plan to migrate to New Azure media service in other subscription. we try to use the tools finish it. When we select target media account in export to another azure media account, we get issue "error when connecting to account". would you please help us check the issue? 
BTW, We have about 2000+ asset neeg migrate, would you please add "select all" option?
![image](https://user-images.githubusercontent.com/26422656/45273904-5f0e0700-b4e7-11e8-8b43-a18ae647019d.png)

**Comment by xpouyat** [comment]
Hello,
I am trying to reproduce the issue. How is configured njkfqmedia ? Is it using AAD with Service Principal or Interactive Mode ? Did you configure the storage key for this account in the login window, when AMSE starts ?

**Comment by tcbjc** [comment]
Hi @xpouyat , We just create njkfqmedia media service account, which manage by media servcie explorer. Source Media Account and Target Media Account configure the their storage key. The two media account belong to different subsrciption in different contract.
![image](https://user-images.githubusercontent.com/26422656/45341324-cf428880-b5cc-11e8-8630-40d1c00715bc.png)

**Comment by xpouyat** [comment]
Closing. Please reopen an issue if you still hit the problem.
