### ISSUE TITLE
Delete asset with dyamic encryption, locators only deletes the keys and policies - does not delete the asset.

### ISSUE THREAD

**Issue by CarlosOnline** [Azure/Azure-Media-Services-Explorer#96]
Delete asset only deletes the keys and policies - does not delete the asset.
I have to click Delete asset a 2nd time to delete the asset.

**Comment by xpouyat** [comment]
Hello,
I am not able to reproduce the issue. Do you use the latest version of AMSE ?
Do you delete the keys and policies when deleting the asset or not ?
Thanks

**Comment by xpouyat** [comment]
Issue closed. Please reopen an new issue if the problem persists.
