### ISSUE TITLE
Asset Filter with spaces in name cannot be played with Azure Media Player.  Taking out the spaces works.

### ISSUE THREAD

**Issue by CarlosOnline** [Azure/Azure-Media-Services-Explorer#97]
Asset Filter with spaces in name cannot be played with Azure Media Player.  Taking out the spaces works.

The problem is that the player is escaping the filter name, which fails the look up.

Please fix player to play asset filters with names or special characters in name.

**Broken Examples:**
https://myaccount.streaming.mediaservices.windows.XXXXX.ism/manifest(filter=Abc 123)
https://myaccount.streaming.mediaservices.windows.XXXXX.ism/manifest(filter=Abc%20123)

**Working example - no space in filter name**
https://myaccount.streaming.mediaservices.windows.XXXXX.ism/manifest(filter=Abc123)

**Comment by xpouyat** [comment]
Closing the issue as this GitHub repo is for AMSE, not AMP.
