### ISSUE TITLE
Tech Question: Ports and domains accessed by AMSE

### ISSUE THREAD

**Issue by otnaicus** [Azure/Azure-Media-Services-Explorer#98]
Hi,

I was wondering if the developers or anybody here could share the ports and/or domains that AMSE connects to? I'm working from behind a tightly controlled environment and my IT Team requires this info to configure our firewalls.

Thanks.

**Comment by xpouyat** [comment]
Sorry, I don't have this info as AMSE use several SDKs. Communication is based on http and https, but I don't know the domains.
