### ISSUE TITLE
Tech: AMSE Crashes upon upload

### ISSUE THREAD

**Issue by DanielEgan** [Azure/Azure-Media-Services-Explorer#99]
I am trying to upload a file to my account and it instantly crashes.  Here are the details.

`
ee the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: Unauthorized
   at System.Data.Services.Client.QueryResult.ExecuteQuery()
   at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   --- End of inner exception stack trace ---
   at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at System.Data.Services.Client.DataServiceQuery`1.Execute()
   at System.Data.Services.Client.DataServiceQuery`1.GetEnumerator()
   at Microsoft.WindowsAzure.MediaServices.Client.MediaQueryable`2.GetEnumerator()
   at Microsoft.WindowsAzure.MediaServices.Client.BaseCollection`1.GetEnumerator()
   at AMSExplorer.UploadOptions.ControlsResetToDefault()
   at AMSExplorer.UploadOptions..ctor(CloudMediaContext myContext, Boolean multifilesMode)
   at AMSExplorer.Mainform.DoMenuUploadFromSingleFileS_Step2(String[] FileNames)
   at AMSExplorer.Mainform.DoMenuUploadFromSingleFiles_Step1()
   at AMSExplorer.Mainform.fromASingleFileToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AMSExplorer
    Assembly Version: 4.3.3.0
    Win32 Version: 4.3.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/AMSExplorer.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.WindowsAzure.MediaServices.Client
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.WindowsAzure.MediaServices.Client.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
Microsoft.Rest.ClientRuntime.Azure.Authentication
    Assembly Version: 2.0.0.0
    Win32 Version: 2.3.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Rest.ClientRuntime.Azure.Authentication.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.2.21924
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.WindowsAzure.MediaServices.Client.Common.Authentication
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.WindowsAzure.MediaServices.Client.Common.Authentication.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 3.19.8.16603
    Win32 Version: 3.19.50615.2240
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.Data.Services.Client
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4.63386
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Data.Services.Client.DLL
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
Microsoft.Practices.TransientFaultHandling.Core
    Assembly Version: 5.1.1209.0
    Win32 Version: 5.1.1209.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Practices.TransientFaultHandling.Core.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.Data.Edm
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4.63386
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Data.Edm.DLL
----------------------------------------
Microsoft.Data.OData
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4.63386
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Data.OData.DLL
----------------------------------------
System.Spatial
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4.63386
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/System.Spatial.DLL
----------------------------------------
Microsoft.WindowsAzure.Storage
    Assembly Version: 9.3.2.0
    Win32 Version: 9.3.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.WindowsAzure.Storage.DLL
----------------------------------------
Microsoft.Azure.Management.Media
    Assembly Version: 0.1.0.0
    Win32 Version: 0.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Azure.Management.Media.DLL
----------------------------------------
Microsoft.Rest.ClientRuntime
    Assembly Version: 2.0.0.0
    Win32 Version: 2.3.15.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Rest.ClientRuntime.DLL
----------------------------------------
Microsoft.Rest.ClientRuntime.Azure
    Assembly Version: 3.0.0.0
    Win32 Version: 3.3.16.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Rest.ClientRuntime.Azure.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3101.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Data.SqlXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.Azure.KeyVault.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.Azure.KeyVault.Core.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.WindowsAzure.MediaServices.Client.Extensions
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Corporation/Azure%20Media%20Services%20Explorer/Microsoft.WindowsAzure.MediaServices.Client.Extensions.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

`

**Comment by xpouyat** [comment]
Hello,
In order to help me to reproduce it, can you send me screenshots of the steps that lead to the crash ? Please send them to xpouyat @ microsoft.com
Thanks

**Comment by xpouyat** [comment]
No answer on my question. Closing the issue.
